FROM nginx:latest


# copy nginx config file

#WORKDIR /app
COPY nginx.conf /etc/nginx/nginx.conf


# copy artifact build from the 'build environment'

COPY  onchangeDemo /usr/share/nginx/html/

# expose port 80

EXPOSE 81

#run nginx
CMD ["nginx", "-g", "daemon off;"]
